name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract Version Information
      id: extract_version
      run: |
        major_version=$(grep 'public const string Major' ./VersionInfo.cs | grep -o '[0-9]\+')
        minor_version=$(grep 'public const string Minor' ./VersionInfo.cs | grep -o '[0-9]\+')
        patch_version=$(grep 'public const string Patch' ./VersionInfo.cs | grep -o '[0-9]\+')
        echo "MAJOR_VERSION=$major_version" >> $GITHUB_ENV
        echo "MINOR_VERSION=$minor_version" >> $GITHUB_ENV
        echo "PATCH_VERSION=$patch_version" >> $GITHUB_ENV

    - name: Define Image Tag
      id: define_tag
      run: |
        IMAGE_TAG="PROD.${{ env.MAJOR_VERSION }}.${{ env.MINOR_VERSION }}.${{ env.PATCH_VERSION }}"
        echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/zd-article-grabber:${{ env.IMAGE_TAG }} .
        docker push ${{ secrets.DOCKER_USERNAME }}/zd-article-grabber:${{ env.IMAGE_TAG }}

    - name: Add SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to server
      run: |
          ssh -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          set -e  # Exit on any error
          IMAGE_TAG="${{ env.IMAGE_TAG }}"
          TIMESTAMP="${{ env.TIMESTAMP }}"
          version="PROD.${{ env.MAJOR_VERSION }}.${{ env.MINOR_VERSION }}.${{ env.PATCH_VERSION }}"
          container_name="$version"

          # Stop the current container
          current_container=$(docker ps -q --filter "name=PROD")
          if [ ! -z "$current_container" ]; then
            docker stop $current_container
          fi

          # Run the new container and capture output
          if ! output=$(docker run -d -p 8080:80 -p 8443:443 \
          --name $container_name \
          # bind mount volumes
          -v /var/www/bepio/api/source:/api/source \
          -v /etc/letsencrypt/live/bepio.net/fullchain.pem:/etc/letsencrypt/live/bepio.net/fullchain.pem:ro \
          -v /etc/letsencrypt/live/bepio.net/privkey.pem:/etc/letsencrypt/live/bepio.net/privkey.pem:ro \
          ${{ secrets.DOCKER_USERNAME }}/zd-article-grabber:${{ env.IMAGE_TAG }} 2>&1); then
            echo "Docker run command failed with the following error:"
            echo "$output"
            exit 1
          fi
          echo "Containers before removal:"
          docker ps -a --filter "name=PROD"
          
          #clean up old containers if more than 1 exists
          container_count=$(docker ps -a --filter "name=PROD" -q | wc -l)
          
          if [ "$container_count" -gt 1 ]; then
            old_containers=$(docker ps -a --filter "name=PROD" \
            --format "{{.ID}} {{.CreatedAt}}" \
            | sort -k2,2r \
            | tail -n +4 \
            | awk '{print $1}')

            if [ ! -z "$old_containers" ]; then
              docker rm -f $old_containers
            fi
          fi

          # Clean up old images if more than 1 exists
          image_count=$(docker images ${{ secrets.DOCKER_USERNAME }}/zd-article-grabber --format "{{.ID}}" | wc -l)

          # Only run cleanup if more than one image is found
          if [ "$image_count" -gt 1 ]; then
            old_images=$(docker images ${{ secrets.DOCKER_USERNAME }}/zd-article-grabber \
            --format "{{.ID}} {{.CreatedAt}}" \
            | sort -k2,2r \
            | tail -n +4 \
            | awk '{print $1}')

            if [ ! -z "$old_images" ]; then
              docker rmi -f $old_images
            fi
          fi
          EOF
